# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from three_omuni/button.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class button(genpy.Message):
  _md5sum = "c703a9d0e274f7444bd1093549d0f0d5"
  _type = "three_omuni/button"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float64 move_angle
float64 move_speed
bool turn_right
bool turn_left
bool arm_data
bool calibration

"""
  __slots__ = ['move_angle','move_speed','turn_right','turn_left','arm_data','calibration']
  _slot_types = ['float64','float64','bool','bool','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       move_angle,move_speed,turn_right,turn_left,arm_data,calibration

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(button, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.move_angle is None:
        self.move_angle = 0.
      if self.move_speed is None:
        self.move_speed = 0.
      if self.turn_right is None:
        self.turn_right = False
      if self.turn_left is None:
        self.turn_left = False
      if self.arm_data is None:
        self.arm_data = False
      if self.calibration is None:
        self.calibration = False
    else:
      self.move_angle = 0.
      self.move_speed = 0.
      self.turn_right = False
      self.turn_left = False
      self.arm_data = False
      self.calibration = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2d4B().pack(_x.move_angle, _x.move_speed, _x.turn_right, _x.turn_left, _x.arm_data, _x.calibration))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 20
      (_x.move_angle, _x.move_speed, _x.turn_right, _x.turn_left, _x.arm_data, _x.calibration,) = _get_struct_2d4B().unpack(str[start:end])
      self.turn_right = bool(self.turn_right)
      self.turn_left = bool(self.turn_left)
      self.arm_data = bool(self.arm_data)
      self.calibration = bool(self.calibration)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2d4B().pack(_x.move_angle, _x.move_speed, _x.turn_right, _x.turn_left, _x.arm_data, _x.calibration))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 20
      (_x.move_angle, _x.move_speed, _x.turn_right, _x.turn_left, _x.arm_data, _x.calibration,) = _get_struct_2d4B().unpack(str[start:end])
      self.turn_right = bool(self.turn_right)
      self.turn_left = bool(self.turn_left)
      self.arm_data = bool(self.arm_data)
      self.calibration = bool(self.calibration)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2d4B = None
def _get_struct_2d4B():
    global _struct_2d4B
    if _struct_2d4B is None:
        _struct_2d4B = struct.Struct("<2d4B")
    return _struct_2d4B
