// Generated by gencpp from file motor_serial/motor_serial.msg
// DO NOT EDIT!


#ifndef MOTOR_SERIAL_MESSAGE_MOTOR_SERIAL_H
#define MOTOR_SERIAL_MESSAGE_MOTOR_SERIAL_H

#include <ros/service_traits.h>


#include <motor_serial/motor_serialRequest.h>
#include <motor_serial/motor_serialResponse.h>


namespace motor_serial
{

struct motor_serial
{

typedef motor_serialRequest Request;
typedef motor_serialResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct motor_serial
} // namespace motor_serial


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::motor_serial::motor_serial > {
  static const char* value()
  {
    return "145fd4bef55a3bc00166d50e6ebdc608";
  }

  static const char* value(const ::motor_serial::motor_serial&) { return value(); }
};

template<>
struct DataType< ::motor_serial::motor_serial > {
  static const char* value()
  {
    return "motor_serial/motor_serial";
  }

  static const char* value(const ::motor_serial::motor_serial&) { return value(); }
};


// service_traits::MD5Sum< ::motor_serial::motor_serialRequest> should match 
// service_traits::MD5Sum< ::motor_serial::motor_serial > 
template<>
struct MD5Sum< ::motor_serial::motor_serialRequest>
{
  static const char* value()
  {
    return MD5Sum< ::motor_serial::motor_serial >::value();
  }
  static const char* value(const ::motor_serial::motor_serialRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::motor_serial::motor_serialRequest> should match 
// service_traits::DataType< ::motor_serial::motor_serial > 
template<>
struct DataType< ::motor_serial::motor_serialRequest>
{
  static const char* value()
  {
    return DataType< ::motor_serial::motor_serial >::value();
  }
  static const char* value(const ::motor_serial::motor_serialRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::motor_serial::motor_serialResponse> should match 
// service_traits::MD5Sum< ::motor_serial::motor_serial > 
template<>
struct MD5Sum< ::motor_serial::motor_serialResponse>
{
  static const char* value()
  {
    return MD5Sum< ::motor_serial::motor_serial >::value();
  }
  static const char* value(const ::motor_serial::motor_serialResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::motor_serial::motor_serialResponse> should match 
// service_traits::DataType< ::motor_serial::motor_serial > 
template<>
struct DataType< ::motor_serial::motor_serialResponse>
{
  static const char* value()
  {
    return DataType< ::motor_serial::motor_serial >::value();
  }
  static const char* value(const ::motor_serial::motor_serialResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOTOR_SERIAL_MESSAGE_MOTOR_SERIAL_H
