// Generated by gencpp from file motor_serial/motor_serialResponse.msg
// DO NOT EDIT!


#ifndef MOTOR_SERIAL_MESSAGE_MOTOR_SERIALRESPONSE_H
#define MOTOR_SERIAL_MESSAGE_MOTOR_SERIALRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace motor_serial
{
template <class ContainerAllocator>
struct motor_serialResponse_
{
  typedef motor_serialResponse_<ContainerAllocator> Type;

  motor_serialResponse_()
    : data(0)  {
    }
  motor_serialResponse_(const ContainerAllocator& _alloc)
    : data(0)  {
  (void)_alloc;
    }



   typedef int16_t _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::motor_serial::motor_serialResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::motor_serial::motor_serialResponse_<ContainerAllocator> const> ConstPtr;

}; // struct motor_serialResponse_

typedef ::motor_serial::motor_serialResponse_<std::allocator<void> > motor_serialResponse;

typedef boost::shared_ptr< ::motor_serial::motor_serialResponse > motor_serialResponsePtr;
typedef boost::shared_ptr< ::motor_serial::motor_serialResponse const> motor_serialResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::motor_serial::motor_serialResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::motor_serial::motor_serialResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace motor_serial

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::motor_serial::motor_serialResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motor_serial::motor_serialResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motor_serial::motor_serialResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motor_serial::motor_serialResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motor_serial::motor_serialResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motor_serial::motor_serialResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::motor_serial::motor_serialResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8524586e34fbd7cb1c08c5f5f1ca0e57";
  }

  static const char* value(const ::motor_serial::motor_serialResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8524586e34fbd7cbULL;
  static const uint64_t static_value2 = 0x1c08c5f5f1ca0e57ULL;
};

template<class ContainerAllocator>
struct DataType< ::motor_serial::motor_serialResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "motor_serial/motor_serialResponse";
  }

  static const char* value(const ::motor_serial::motor_serialResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::motor_serial::motor_serialResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 data\n\
\n\
";
  }

  static const char* value(const ::motor_serial::motor_serialResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::motor_serial::motor_serialResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct motor_serialResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::motor_serial::motor_serialResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::motor_serial::motor_serialResponse_<ContainerAllocator>& v)
  {
    s << indent << "data: ";
    Printer<int16_t>::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOTOR_SERIAL_MESSAGE_MOTOR_SERIALRESPONSE_H
