// Generated by gencpp from file motor_serial/motor_serialRequest.msg
// DO NOT EDIT!


#ifndef MOTOR_SERIAL_MESSAGE_MOTOR_SERIALREQUEST_H
#define MOTOR_SERIAL_MESSAGE_MOTOR_SERIALREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace motor_serial
{
template <class ContainerAllocator>
struct motor_serialRequest_
{
  typedef motor_serialRequest_<ContainerAllocator> Type;

  motor_serialRequest_()
    : id(0)
    , cmd(0)
    , data(0)  {
    }
  motor_serialRequest_(const ContainerAllocator& _alloc)
    : id(0)
    , cmd(0)
    , data(0)  {
  (void)_alloc;
    }



   typedef uint8_t _id_type;
  _id_type id;

   typedef uint8_t _cmd_type;
  _cmd_type cmd;

   typedef int16_t _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::motor_serial::motor_serialRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::motor_serial::motor_serialRequest_<ContainerAllocator> const> ConstPtr;

}; // struct motor_serialRequest_

typedef ::motor_serial::motor_serialRequest_<std::allocator<void> > motor_serialRequest;

typedef boost::shared_ptr< ::motor_serial::motor_serialRequest > motor_serialRequestPtr;
typedef boost::shared_ptr< ::motor_serial::motor_serialRequest const> motor_serialRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::motor_serial::motor_serialRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::motor_serial::motor_serialRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace motor_serial

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::motor_serial::motor_serialRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motor_serial::motor_serialRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motor_serial::motor_serialRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motor_serial::motor_serialRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motor_serial::motor_serialRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motor_serial::motor_serialRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::motor_serial::motor_serialRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c12664693d384a430f1b8caa7efe0e71";
  }

  static const char* value(const ::motor_serial::motor_serialRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc12664693d384a43ULL;
  static const uint64_t static_value2 = 0x0f1b8caa7efe0e71ULL;
};

template<class ContainerAllocator>
struct DataType< ::motor_serial::motor_serialRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "motor_serial/motor_serialRequest";
  }

  static const char* value(const ::motor_serial::motor_serialRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::motor_serial::motor_serialRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 id\n\
uint8 cmd\n\
int16 data\n\
";
  }

  static const char* value(const ::motor_serial::motor_serialRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::motor_serial::motor_serialRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.cmd);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct motor_serialRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::motor_serial::motor_serialRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::motor_serial::motor_serialRequest_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id);
    s << indent << "cmd: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.cmd);
    s << indent << "data: ";
    Printer<int16_t>::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOTOR_SERIAL_MESSAGE_MOTOR_SERIALREQUEST_H
